### ISSUE TITLE
So ... how do you actually run this 

### ISSUE THREAD

**Issue by 1Azami1** [waicool20/WAI2K#1]
So huhhh, even though I have a vast knowledge on a number of subjects pertaining to this world, I've been struggling ever since yesterday trying to find ways to actually run this, to no avail sadly. 

Would you be so kind as to give assistance to an humble man such as me ? 🤔

**Comment by waicool20** [comment]
WAI2K is currently experimental and work in progress, therefore I've decided to withheld the readmes and other documentation until it is in a somewhat stable and usable state. The main purpose of the repo as it is now is just for reference and progress tracking for the members in my discord server. 

Logistics Support are implemented but are still being tweaked and is not feature complete.

In any case the main part is getting android ADB on the path then compiling the project to obtain a jar executable. You also need sikulix and an emulator with 2160x1080 resolution.

You're welcome to join this discord server if you want any further hints: https://discord.gg/2tt5Der

I'll release documentation when the project is done. Until then happy exploring.
