### ISSUE TITLE
can you tell me how to use it

### ISSUE THREAD

**Issue by lkq13905940077** [waicool20/WAI2K#17]

**Comment by Mirsem13** [comment]
Hi, can you tell me how to use it on Linux?

**Comment by waicool20** [comment]
I'm currently trying to replace the image matching library with my own, might need to wait on that, almost done though

You can set up the emulator first in the meanwhile, best you use android studios emulator and create one with 2160x1080 resolution

**Comment by waicool20** [comment]
@Mirsem13 the latest commit in the cvauto-rewrite branch: c9d37572ca667384bc3375d995c5e18dbcc474ed is under testing and should be working under the latest GFL version with the new UI.

**Comment by waicool20** [comment]
Closing this since there should be sufficient information in the README now
