### ISSUE TITLE
Error when launching the jar executable

### ISSUE THREAD

**Issue by 1Azami1** [waicool20/WAI2K#2]
Henlo, it's me again. 
Every time I try to run the jar executable, I always get these errors and I'm kinda at a loss in regards to what might be causing them 

![capture](https://user-images.githubusercontent.com/16174152/43058676-c8cb839a-8e16-11e8-8773-a47731311550.PNG)

**Comment by waicool20** [comment]
Is your `adb` on system path?

**Comment by 1Azami1** [comment]
It now is and the program is now running perfectly.

Guess this is it for my questions then, thank you for your support and have a nice day. :)
